### PR TITLE
add incognito page

### PR DESCRIPTION
**Pull request by ring04h**
Support browser contexts to launch different sessions #44

### CODE REVIEW

**Comment by miyakogi** [comment]
Thank you for PR, but sorry, I don't want to add original api which puppeteer does not have as possible.
Does puppeteer have a plan to add this method?

**Comment by ring04h** [comment]
@miyakogi 

puppeteer new features are queued, see: https://github.com/GoogleChrome/puppeteer/issues/85

A viable user scenario might be testing several users logged in simultaneously into the service.
We might expose browser contexts as a string literal option to the browser.newPage:

```javascript
browser.newPage(); // creates a new page in a default browser context
browser.newPage({ context: 'default' }); // same as previous call
browser.newPage({ context: 'another-context' }); // creates a page in another browser context
```

**Comment by miyakogi** [comment]
Thank you for information.
I agree with this feature is useful.
But this PR implements `Browser.newIncognitoPage()`, which is different from puppeteer's api.

**Comment by ring04h** [comment]
Okay, then I close this pull.

**Pull request closed without merging**
