### PR TITLE
Exit correctly

### PR DESCRIPTION
**Pull request by scp10011**
1.Detect connection availability from the second transmission
2.Prevent infinite hangs due to browser crashes or network anomaly

### CODE REVIEW

**Comment by miyakogi** [comment]
Thank you for PR!
It looks very good to me.

I have one question.
How about changing log level to warning or error?

**Comment by miyakogi** [comment]
Sorry, one more suggestion.
How about changing log message to 'connection unexpectedly closed'?

**Comment by scp10011** [comment]
ok

**Comment by miyakogi** [comment]
Thank you for updating and adding test!

Why closed this PR?
I want to merge this PR.
Although some errors are reported by CI, I will fix them after merging this PR.

**Comment by miyakogi** [comment]
No problem!
Thank you!

**Pull request merged**
