### PR TITLE
use urllib3.stream instead of urllib.request

### PR DESCRIPTION
**Pull request by HuberTRoy**
Almost all Pythoner will install `pip`.
`urllib3` in the folder of  `pip`, so we can use it directly.
`pip` also have a process bar when downloading library, we can use it directly too.

### CODE REVIEW

**Comment by miyakogi** [comment]
Thank you for PR!
Showing progress bar is good idea!

However, I have some requests to this PR.

First, I don't want to depend on inside of pip, since these modules/functions may be changed in the future release. How about simply installing urllib3 and progress bar library like [tqdm](https://github.com/tqdm/tqdm) in the setup.py?

Second, currently actual download process seems to be done in the `extract_zip` function. Can you move this into `download_zip` function before printing `"chromium download done."` message?

Third, please do not change too much things, such as adding parentheses, changing positions of line breaks, and changing quotation type of docstrings, if not relevant to implementing this feature.

Fourth, please check styles before committing your changes. It can be done as follows:

1. `git clone https://github.com/miyakogi/pyppeteer && cd pyppeteer`
2. make virtual environment and activate it.
3. `pip install -e .` and `pip install -r requirements-dev.txt`
4. make new branch.
5. write your code.
6. run tests: `pytest` or `python -m unittest discover`
7. run checks: `doit`

Thank you!

**Comment by HuberTRoy** [comment]
@miyakogi 
Sorry, I guess you don't use `urllib3`  because don't want more requirements so that I use `pip`.
I use `urllib3` for streaming data and `tqdm` for process bar now and added them to `setup.py`.
`pytest` and `doit` have test pass on my computer.
: )

**Comment by HuberTRoy** [comment]
@miyakogi 
You are right, it's my oversight, sorry.

**Comment by miyakogi** [comment]
Perfect!
Nice work!
Thank you!

**Pull request merged**
